### ISSUE TITLE
Javadoc is not exported in maven scripts

### ISSUE THREAD

**Issue by dominicdesu** [openhab/jupnp#16]
Hi,

I get a "Note: This element has no attached Javadoc and the Javadoc could not be found in the attached source." for jupnp classes in the default IDE setup of OH2.

I am not an expert in that matter but it seems as if the javadoc of jupnp is not exported in the maven scripts and is therefore not available in OH2.

**Comment by kaikreuzer** [comment]
Thanks, indeed the update site was lacking the sources for the features. Will update it after creating a new jupnp build and include the sources in the openHAB 2 target platform then!
